### ISSUE TITLE
Crash on startup - 1.19.2 fabric 0.15.7

### ISSUE THREAD

**Issue by KhawanC** [anar4732/ProgressiveBossesFabric#2]
When i try to load the server with this mod I got the error:

```
[12:55:31] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'progressivebosses'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.NoSuchFieldError: checkbox
	at me.lortseam.completeconfig.data.BooleanEntry.<init>(BooleanEntry.java:26) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Entry.create(Entry.java:49) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.EntrySet.lambda$resolve$1(EntrySet.java:31) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at me.lortseam.completeconfig.data.EntrySet.resolve(EntrySet.java:32) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:58) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.ClusterSet.resolve(ClusterSet.java:13) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:108) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Parent.lambda$resolveContainer$7(Parent.java:101) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:101) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.ClusterSet.resolve(ClusterSet.java:13) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:108) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Parent.lambda$resolveContainer$7(Parent.java:101) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:101) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.ClusterSet.resolve(ClusterSet.java:13) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:108) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Config.lambda$new$0(Config.java:52) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Config.deserialize(Config.java:94) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at me.lortseam.completeconfig.data.Config.load(Config.java:121) ~[completeconfig-base-2.0.1-7d97f7f42fce4d93.jar:?]
	at insane96mcp.progressivebosses.utils.AConfig.load2(AConfig.java:17) ~[ProgressiveBossesFabric-1.19.2-U2.jar:?]
	at insane96mcp.progressivebosses.ProgressiveBosses.onInitialize(ProgressiveBosses.java:56) ~[ProgressiveBossesFabric-1.19.2-U2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	... 7 more
```

any suggestion?

if someone need any detail just ask

**Comment by kineticV** [comment]
@anar4732  I'm getting this same issue. I tested and it only occurs with Fabric loader versions over 0.15.0. Version 0.14.25 and lower work fine with it. This is with Fabric 1.19.2.

I need to be on a higher version of the loader because some mods require it, but I can't use Progressive Bosses then.

**Comment by anar4732** [comment]
@kineticV It's actually a bug of completeconfig. [Go ask them for a fix.](https://github.com/Lortseam/completeconfig/issues/26)
